name: trinity

services:
  db:
    image: postgres:16
    container_name: trinity_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: trinity-back
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
